Repository codesquad-memeber-2020/vm-5, pull requests merged in 2020-03, with the labels that each got.

#11 CSS 작업 완료
  css/reset.css
  css/style.css
  index.html
  package-lock.json
  package.json
  scss/style.scss
Labels: css, html

#12 Style, Docs: 스타일 일부 수정 및 Readme 추가
  README.md
  css/style.css
  index.html
  scss/style.scss
Labels: css

#13 Model 설계 및 여러 기능 추가
  .gitignore
  index.html
  src/action/coinAction.js
  src/action/numberButtonAction.js
  src/main.js
  src/model/model.js
  src/model/vendingMachineModel.js
  src/model/walletModel.js
  src/util/constants.js
  src/util/mockItemData.js
  src/util/util.js
  src/view/productView.js
  src/view/selectView.js
  src/view/walletView.js
Labels: JavaScript

#14 Feature select
  css/style.css
  scss/style.scss
  src/model/vendingMachineModel.js
  src/util/constants.js
  src/util/util.js
  src/view/productView.js
  src/view/selectView.js
  src/view/walletView.js
Labels: CSS, JavaScript

#16 Feature changes
  src/action/changeAction.js
  src/main.js
  src/model/changeModel.js
  src/model/vendingMachineModel.js
  src/model/walletModel.js
Labels: JavaScript

#17 Feature select
  css/style.css
  scss/style.scss
  src/model/vendingMachineModel.js
  src/util/constants.js
  src/view/productView.js
  src/view/selectView.js
Labels: CSS, HTML, JavaScript

#18 잔돈 반환 알고리즘
  babel.config.js
  package-lock.json
  package.json
  src/util/constants.js
  src/util/util.js
  test/calculateCoins.test.js
  test/changes.test.js
Labels: JavaScript

#20 잔돈 반환 기능 추가
  src/model/changeModel.js
  src/model/vendingMachineModel.js
  src/model/walletModel.js
  src/util/constants.js
  src/view/productView.js
  src/view/selectView.js
  src/view/walletView.js
Labels: JavaScript

#22 문서화 작업
  document/%EA%B5%AC%EB%8F%85%EC%9E%90%EB%A5%BC%20%EB%8B%B4%EC%9D%84%20Set%EC%9D%84%20%EC%83%9D%EC%84%B1%ED%95%A9%EB%8B%88%EB%8B%A4..html
  document/ChangeModel.html
  document/Model.html
  document/ProductView.html
  document/SelectView.html
  document/VendingMachineModel.html
  document/WalletModel.html
  document/WalletView.html
  document/fonts/Montserrat/Montserrat-Bold.eot
  document/fonts/Montserrat/Montserrat-Bold.ttf
  document/fonts/Montserrat/Montserrat-Bold.woff
  document/fonts/Montserrat/Montserrat-Bold.woff2
  document/fonts/Montserrat/Montserrat-Regular.eot
  document/fonts/Montserrat/Montserrat-Regular.ttf
  document/fonts/Montserrat/Montserrat-Regular.woff
  document/fonts/Montserrat/Montserrat-Regular.woff2
  document/fonts/Source-Sans-Pro/sourcesanspro-light-webfont.eot
  document/fonts/Source-Sans-Pro/sourcesanspro-light-webfont.svg
  document/fonts/Source-Sans-Pro/sourcesanspro-light-webfont.ttf
  document/fonts/Source-Sans-Pro/sourcesanspro-light-webfont.woff
  document/fonts/Source-Sans-Pro/sourcesanspro-light-webfont.woff2
  document/fonts/Source-Sans-Pro/sourcesanspro-regular-webfont.eot
  document/fonts/Source-Sans-Pro/sourcesanspro-regular-webfont.svg
  document/fonts/Source-Sans-Pro/sourcesanspro-regular-webfont.ttf
  document/fonts/Source-Sans-Pro/sourcesanspro-regular-webfont.woff
  document/fonts/Source-Sans-Pro/sourcesanspro-regular-webfont.woff2
  document/global.html
  document/index.html
  document/scripts/collapse.js
  document/scripts/linenumber.js
  document/scripts/nav.js
  document/scripts/polyfill.js
  document/scripts/prettify/Apache-License-2.0.txt
  document/scripts/prettify/lang-css.js
  document/scripts/prettify/prettify.js
  document/scripts/search.js
  document/styles/jsdoc.css
  document/styles/prettify.css
  jsdoc.json
  package-lock.json
  package.json
  src/model/changeModel.js
  src/model/model.js
  src/model/vendingMachineModel.js
  src/model/walletModel.js
  src/util/constants.js
  src/util/fetch.js
  src/util/util.js
  src/view/productView.js
  src/view/selectView.js
  src/view/walletView.js
Labels: Docs

#23 [상품 선택, 지갑] 상품 구매 기능 추가
  src/model/model.js
  src/model/vendingMachineModel.js
  src/util/util.js
  src/view/productView.js
Labels: JavaScript

#24 상품 구매 애니메이션 기능 추가 및 코드 가독성 향상 작업
  css/style.css
  scss/style.scss
  src/model/vendingMachineModel.js
  src/model/walletModel.js
  src/util/constants.js
  src/view/productView.js
Labels: CSS, JavaScript

#25 Fix: 클래스명 상수화
  src/util/constants.js
  src/view/productView.js
  src/view/selectView.js
Labels: JavaScript

#26 Docs: 문서화 작업 진행 완료
  src/model/vendingMachineModel.js
  src/util/constants.js
  src/view/productView.js
Labels: Docs

#28 문서화 파일 미생성으로 인한 재배포
  document/ChangeModel.html
  document/Model.html
  document/ProductView.html
  document/SelectView.html
  document/VendingMachineModel.html
  document/WalletModel.html
  document/WalletView.html
  document/global.html
  document/index.html
  src/model/walletModel.js
Labels: Docs
